### ISSUE TITLE
SourceUrl="weatherforecast" from the getting started sample is not working 

### ISSUE THREAD

**Issue by afofanov** [Akinzekeel/BlazorGrid#44]

**Comment by Akinzekeel** [comment]
I assume you are referring to the WebAssembly tutorial since I haven't got around to writing the one for Server-Side yet.

Looking at the docs, perhaps the SourceUrl is missing the /api (so it should be /api/weatherforecast instead of just weatherforecast). Could you try that and report back please?

**Comment by afofanov** [comment]
Hi Majid,

It looks like SourceUrl is not working at all, but I was able to modify
Custom Provider to work with backend.
Something strange happening, somehow can't get data out off
BlazorGridResults<T>. Always getting a result structure with total count 0,
and Data list empty.
I thought if you can show working server side Employee controller I can see
if I'm doing it correctly.

Thank you,
Art

**Comment by Akinzekeel** [comment]
Thanks for bringing this to my attention. I almost forgot it, but yes the SourceUrl has no effect. This was used in an earlier version of BlazorGrid, however the most recent version dropped the SourceUrl parameter in favor of a Provider delegate (similar to the Virtualize component's ItemsProvider). This is so that BlazorGrid has no dependency on Json and you are free to use any other method of transport such as gRPC instead.

I will be correcting this in the documents soon. In the mean time, if you can share your code I'll be happy to help.

**Comment by afofanov** [comment]
Great, thanks!

**Comment by Akinzekeel** [comment]
I've just updated the Getting Started page. Please have a look and feel free to open a new issue if you run into any problems.
